# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 20:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deviceName', models.CharField(blank=True, default='', max_length=100)),
                ('advertising_id', models.CharField(blank=True, default='', max_length=100)),
                ('idfa', models.CharField(blank=True, default='', max_length=100)),
                ('appsflyer_int', models.BooleanField(default=False)),
                ('bundle_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
