# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apps',
            name='advertising_id',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='appsflyer_int',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='bundle_id',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='deviceName',
        ),
        migrations.RemoveField(
            model_name='apps',
            name='idfa',
        ),
        migrations.AddField(
            model_name='apps',
            name='amplitude_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='appsflyer_api_key',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
