# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180513_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='timeUpdated',
            field=models.DateField(auto_now=True),
        ),
    ]
