# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180515_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to=settings.AUTH_USER_MODEL),
        ),
    ]
