# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180516_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='app_id',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
