# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_apps_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='ios_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apps',
            name='store_url',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
