# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180519_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='bundle_id',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apps',
            name='ios_app',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
