# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_apps_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='adjust_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='braze_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='mixpanel_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apps',
            name='urbanairship_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
