# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180520_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='branch_api_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
