# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_apps_branch_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='ios_app',
            field=models.BooleanField(default=True),
        ),
    ]
