# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180520_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='ios_app',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
