# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180520_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='customer_endpoint',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
