# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_apps_customer_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='app_id',
            field=models.TextField(max_length=100),
        ),
    ]
