# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180528_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
