# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
