# Generated by Django 2.0.5 on 2018-06-01 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20180528_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('gdpr_email', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='apps',
            name='image_url',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='apps',
            name='store_url',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
