# Generated by Django 2.0.5 on 2018-06-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20180601_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessors',
            name='sendEmails',
            field=models.BooleanField(default=False),
        ),
    ]
