# Generated by Django 2.0.5 on 2018-06-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_dataprocessors_sendemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessors',
            name='processor_bool_name',
            field=models.TextField(default='bryan@gdprhero.io', max_length=100),
        ),
    ]
