# Generated by Django 2.0.5 on 2018-06-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20180602_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='customer_bool',
            new_name='customer_user_bool',
        ),
    ]
