# Generated by Django 2.0.5 on 2018-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20180602_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprocessors',
            name='processor_bool_name',
            field=models.TextField(default='customer_user_bool', max_length=100),
        ),
    ]
