# Generated by Django 2.0.5 on 2018-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20180602_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessors',
            name='processor_id',
            field=models.TextField(default='customer_user_id', max_length=100),
        ),
    ]
