# Generated by Django 2.0.5 on 2018-06-03 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_dataprocessors_processor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsFlyerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject_request_id', models.CharField(blank=True, max_length=100)),
                ('received_time', models.DateTimeField(blank=True)),
                ('expected_completion_time', models.DateTimeField(blank=True)),
                ('encoded_request', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
