# Generated by Django 2.0.5 on 2018-05-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='advertising_id',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='linenos',
            new_name='appsflyer_int',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
        migrations.AddField(
            model_name='snippet',
            name='deviceName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='idfa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
