# Generated by Django 2.0.5 on 2018-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_snippet_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='bundle_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
