# Generated by Django 2.0.5 on 2018-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20180510_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
