# Generated by Django 2.0.5 on 2018-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_profile_email_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='accountName',
            new_name='companyName',
        ),
        migrations.AddField(
            model_name='profile',
            name='companyWebsite',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
