# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_inboundemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundemail',
            options={},
        ),
        migrations.RemoveField(
            model_name='inboundemail',
            name='created',
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='inboundEmail',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
