# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_auto_20180513_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amplitude_api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='appsflyer_api_key',
        ),
    ]
