# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_auto_20180520_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='app_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
