# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0020_auto_20180528_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
