# Generated by Django 2.0.5 on 2018-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0022_auto_20180530_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='clever_tap_id',
            new_name='clever_tap_user_id',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='fabric_id',
            new_name='fabric_user_id',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='googleAnalytics_id',
            new_name='googleAnalytics_user_id',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='optimizely_id',
            new_name='optimizely_user_id',
        ),
        migrations.AddField(
            model_name='snippet',
            name='subparam1_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='subparam2_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='subparam3_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
