# Generated by Django 2.0.5 on 2018-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0023_auto_20180602_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='iterable_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='leanplum_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
